name: nanobot-new-lato

services:
  nanobot-gateway-new-lato:
    container_name: nanobot-gateway-new-lato
    build:
      context: .
      dockerfile: Dockerfile
    command: ["gateway"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    volumes:
      - ~/.nanobot-new-lato:/home/nanobot/.nanobot
      - ~/work-root/project:/home/nanobot/project
    ports:
      - "18792:18790"
    environment:
      NANOBOT_CHANNEL: telegram
      NANOBOT_BOT_TOKEN: "${NEW_LATO_BOT_TOKEN}"
      NANOBOT_ALLOW_FROM: "${NEW_LATO_ALLOW_FROM}"
      NANOBOT_PROVIDER: "${NEW_LATO_PROVIDER}"
      NANOBOT_MODEL: "${NEW_LATO_MODEL}"
      NANOBOT_API_KEY: "${NEW_LATO_API_KEY}"

  nanobot-cli-new-lato:
    container_name: nanobot-cli-new-lato
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - cli
    stdin_open: true
    tty: true
    volumes:
      - ~/.nanobot-new-lato:/home/nanobot/.nanobot
    command: ["status"]
